### ISSUE TITLE
hang up on mpd events

### ISSUE THREAD

**Issue by fvzeppelin** [Arzk/pitft-playerui#1]
Hello,
first of all: thank you for your work and documentatipn!
I have just installed MPD upon a fresh jessie lite image from adafruit and followed your instructions for the ui. The ui comes up and shows the correct information oncl. cover :)
Unfortunately, if I do any plyer control (touchscreen or via web interface) python grabs the whole cpu. Aftef ~30 sec things get calm again, but the controls don't work :(
Any hints what might go wrong here?

**Comment by artoinoin** [comment]
Sorry for the terribly long delay. I have battled with CPU usage and the changes in development branch reduced it a bit. Could you try if the changes solve the issue?

**Comment by fvzeppelin** [comment]
Thank you for your reply!
Unfortunately, I do not have as test environment as I use Moode which doesn't work with the Adafruit kernel.
So I would propose to close the issue. 

----- Originale Nachricht -----
Von: Arto Oinonen <notifications@github.com>
Gesendet: 03.10.17 - 17:28
An: Arzk/pitft-playerui <pitft-playerui@noreply.github.com>
Betreff: Re: [Arzk/pitft-playerui] hang up on mpd events (#1)
